"""Responses."""


class ResponseCode:
    """The Current Response Code."""

    (RET_OK, RET_HOLD, E_NOT_INITIALIZE, E_NOT_FOUND,
     E_CONNECT, E_MAKE_SOCKET, E_SND_TIMEOUT, E_RCV_TIMEOUT,
     E_RCV_FRAME, E_MEMORY, E_FILM_EMPTY, E_BATTERY_EMPTY,
     E_CAM_POINT, E_MOTOR, E_IMAGE_SIZE_OVER, E_NOT_IMAGE_DATA,
     E_OTHER_USED, E_PRINTING, E_COVER_OPEN, E_EJECTING,
     E_TESTING, E_PI_SENSOR, E_INVALID_PASS, E_UNMATCH_PASS,
     E_CHARGE, E_NOT_SUPPORTED, E_NOT_FIRMWARE_DATA,
     E_FWUPDATE_FAIL, E_FWUPDATING) = range(29)
